### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by Riglo** [schroffl/teamspeak-query#11] opened 2018-04-21 20:49 UTC
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at throttle.run (C:\Users\Administrator\Desktop\TSBot\node_modules\teamspeak-query\index.js:85:19)
    at Map.run (C:\Users\Administrator\Desktop\TSBot\node_modules\teamspeak-query\lib\throttle.js:48:7)
    at TeamspeakQuery.checkQueue (C:\Users\Administrator\Desktop\TSBot\node_modules\teamspeak-query\index.js:80:19)
    at TeamspeakQuery.handleLine (C:\Users\Administrator\Desktop\TSBot\node_modules\teamspeak-query\index.js:121:12)
    at emitOne (events.js:116:13)
    at Carrier.emit (events.js:211:7)
    at C:\Users\Administrator\Desktop\TSBot\node_modules\carrier\lib\carrier.js:24:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

This is my code:
```
const TeamspeakQuery = require('teamspeak-query');
const query = new TeamspeakQuery(queryip, queryport, {port: tport});
query.throttle.set('enable', false);

query.send('login', username, password)
	.then(() => query.send('use', { 'sid': serverid }))
	.then(() => query.send('clientupdate', { 'client_nickname': username }))
	.then(() => query.send('servernotifyregister', { 'event': 'textprivate' }))
	.then(() => console.log('Success.'))
	.catch(err => console.error('Error:', err));

query.on('textmessage', data => {
	for (i = 0; i < 100; i++) {
		query.send('clientpoke', {'clid': data.invokerid, 'msg': 'Test: ' + (i + 1)})
			.catch(err => console.error('Error:', err));
	}
});
```

The IP is whitelisted.
This error only appears when disabling the throttle (line 3).

**Comment by schroffl** [comment] 2018-04-21 21:59
The `This socket has been ended by the other party`-error only ever occured to me when the server cut the connection after a certain timeout (See #9).
I also don't see how the throttling should affect the underlying connection in any way. When the server detects that you went over your limit (which requires you to *not* be whitelisted &mdash; but you are) it only responds with an error and does not destroy the socket as far as I know.

Can you please tell me which version of the library you are using and whether you have an unusual setup?
I suppose in my eyes it almost always qualifies as an <q>Unusual setup</q> if you are using the Teamspeak Query API in any real and/or public environment, which I never did.

**Edit:** Another question: do any of your `clientpoke`-commands actually succeed or do you never see any result?

**Comment by Riglo** [comment] 2018-04-21 22:29
I'm using the latest version 2.1.0.
I have it running on a Windows virtual server, the idea was to have a simple bot to masspoke, massmove, etc. for my guild's TeamSpeak server, if that's what you mean by "setup".

Not disabling the throttling will not end up ending the socket, and all pokes will go through (with the set delay of 10 queries per 3 seconds as set in the library).
If I disable the throttling all pokes will instantly go through, but as soon as it his the last one the above error appears and the socket is ended.

**Edit:** If I remove myself from the whitelist and use the same code as above I only get the error that I'm banned because of flood and the socket stays alive (If that helps figuring out the error)

**Comment by schroffl** [comment] 2018-04-21 23:26
Thanks for the information, it's just that I like to have a little bit more context for tracking down bugs I might not be able to reproduce.

What you are describing sounds really weird. Especially because it runs the commands even when you disable the throttling and then only crashes on the last one. Have you tried using a different amount of `clientpoke`-commands like `10`, `50`, `100`, `200`? If the problem occurs at the same point when sending 200 commands it could actually be some Teamspeak-constraint that I don't yet know about.

I am not familiar with windows virtual servers, but could it be that these impose any limits (e.g. Network I/O)? Although I can hardly imagine this being a problem.

Other than that I would take a look at the server logs and check if they mention anything out of the ordinary.
I will do some testing tomorrow myself and see whether I encounter the same problem on a fresh server.   
But of course I wish you the best of luck to have it resolved by then :)

**Comment by schroffl** [comment] 2018-06-14 10:56
I'm really sorry, but I totally forgot about this issue.
Did you solve your problem eventually?

**Comment by schroffl** [comment] 2018-06-25 09:48
I'm gonna close this issue for now. If you have any further updates feel free to reopen it :)

**Closed as completed by schroffl** 2018-06-25 09:48 UTC
